language: cpp

compiler: gcc

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y build-essential autoconf libtool libpng12-dev libfreetype6-dev

script:
    - autoreconf -i
    - CPPFLAGS="/usr/include/freetype2" ./configure --enable-dedicated-server
    - make -j`nproc`
