language: cpp

compiler:
    - gcc
    - clang

notifications:
  irc:
    channels:
      - "chat.freenode.net#goatattack"
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
    use_notice: true
    skip_join: true

before_install:
    - sudo add-apt-repository -y ppa:zoogie/sdl2-snapshots

install:
    - sudo apt-get -qq update
    - sudo apt-get install -y build-essential autoconf libtool libsdl2-dev libsdl2-mixer-dev libpng12-dev libfreetype6-dev

script:
    - autoreconf -i
    - ./configure --enable-map-editor --enable-non-free-pak
    - make -j`nproc`
    - sudo make install-strip
    - make clean
    - ./configure --enable-dedicated-server --enable-master-server
    - make -j`nproc`
    - sudo make install-strip
