compiler: gcc

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y build-essential autoconf libtool libsdl2-dev libsdl2-mixer-dev libpng12-dev libfreetype6-dev

script:
    - autoreconf -i
    - CPPFLAGS="/usr/include/freetype2" ./configure --enable-map-editor --enable-non-base-pak
    - make -j`nproc`
    - make clean
    - CPPFLAGS="/usr/include/freetype" ./configure --enable-dedicated-server
    - make -j`nproc`
