language: cpp

compiler: gcc

notifications:
    irc: "chat.freenode.net#goatattack"
    use_notice: true

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y build-essential autoconf libtool libpng12-dev libfreetype6-dev

script:
    - autoreconf -i
    - CPPFLAGS="-I/usr/include/freetype2" ./configure --enable-dedicated-server
    - make -j`nproc`
